# Generated by Django 4.2.1 on 2023-08-14 16:30

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_useraccount_image_active_image_duplicate_image_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=home.models.uploaded_file, validators=[home.models.validate_file_size])),
                ('generated', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('duplicate', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.useraccount')),
            ],
        ),
    ]
